version: "3.9"

services:
  income_service:
    build: .
    container_name: ms-income-service
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://fintrack_admin:Vicente5150.@host.docker.internal:3307/fintrack_db
      BACKEND_CORS_ORIGINS: http://localhost:3000,http://127.0.0.1:3000,http://localhost:5500,http://127.0.0.1:5500
    ports:
      - "8002:8000"
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
